spring:
  application:
    name: feign-consumer
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    "UserClient#findUserByUsername(String)":
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
  threadpool:
    default:
      coreSize: 100
